config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources 'achievements'
  root 'welcome#index'
end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true
  enum privacy: [ :public_access, :private_access, :friends_access ]

  def description_html
   Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(description)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy, :update]
  before_action :owners_only, only: [:edit, :update, :destroy]

  def index
    @achievements = Achievement.public_access
  end

  def new
    @achievement = Achievement.new
  end

  def create
    @achievement = Achievement.new(achievement_params)
    @achievement.save ? (redirect_to achievement_url(@achievement.id), notice: "Achievement has been created") : (render :new)
  end

  def edit
  end

  def show
    @achievement = Achievement.find(params[:id])
  end

  def update
    @achievement.update_attributes(achievement_params) ? (redirect_to achievement_path(@achievement)) : (render :edit)
  end

  def destroy
    @achievement.destroy
    redirect_to achievements_path
  end

  private

  def achievement_params
    params.require(:achievement).permit(:title, :description, :privacy, :featured, :cover_image)
  end

  def owners_only
    @achievement = Achievement.find(params[:id])
    current_user != @achievement.user ? redirect_to(achievements_path) : (nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController <  ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/achievements/new.html.erb
<%= simple_form_for @achievement do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :privacy, collection: Hash[Achievement.privacies.map { |k, v| [k.split('_').first.capitalize, k]}] %>
  <%= f.input :featured, label: 'Featured achievement' %>
  <%= f.input :cover_image, as: :file %>
  <%= f.submit 'Create achievement', class: 'btn btn-primary' %>
<% end %>

app/views/achievements/show.html.erb
<h1><%= @achievement.title %></h1>
<div>
  <%= @achievement.description_html.html_safe %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>I Rock</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">I Rock</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to 'New Achievement', new_achievement_path %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
    </nav><!-- /.container-fluid -->
    <% if flash[:notice] %>
      <div class="alert alert-info"><%= flash[:notice] %></div>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome</h1>